### ISSUE TITLE
2016.11.4 lunch

### ISSUE THREAD

**Issue by opst-nemoto** [matsuo-y/git-practice-lunch#17]
connect matsuo-y/git-practice#14

今日の昼ごはんを以下のサイトで公開できる

origin/#{N}-lunchで作業を行い、origin/stagingにPRしてマージする
コミットメッセージは、`fix` を記載しないようにし、誰の昼食か（どんな修正か）がわかる文言にする
PRのタイトルは、`fix` を記載しないようにし、誰の昼食かがわかる文言にする

作業担当者は、下記の通りとする
- issue作成者：根本
- branch作成者：姜
- 開発担当者(昼食報告、1名)：姜
- 検収担当者：上田
- リリース担当者：根本

ステージング環境： https://staging-git-practice-lunch.herokuapp.com/lunch/201611.html
本番環境：　https://matsuo-y.github.io/git-practice-lunch/lunch/201611.html

ただし、PR時ににはPR番号{N}の環境でサイトをブラウザで確認する
PR環境：　https://git-practice-lunch-pr-{N}.herokuapp.com/

issue発行者は、各作業が終わった段階でチェックをつけ、releases/tagsの設定まで終わった段階でこのissueをクローズする
- [x] issue作成
- [x] issue branch作成
- [x] stagingへのPR
- [x] masterへのPR
- [x] masterへのreleases/tags設定

**Comment by jiangheqing** [comment]
@opst-ueda 

お疲れ様です。
本日のランチ予定を記載いたしました。ご確認お願い致します。
[検収担当者：上田]

**Comment by ghost** [comment]
> origin/#{N}-lunchで作業を行い、origin/stagingにPRしてマージする

@jiangheqing  なにブランチつくった？

**Comment by jiangheqing** [comment]
@opst-fujimoto 

#17-lunch と 作業用ブランチ #17-lunch-kan を作りました。PRは下記です。

https://github.com/matsuo-y/git-practice-lunch/pull/18

**Comment by opst-ueda** [comment]
変更内容を確認し、ステージングにマージしました。

@nemoto 
本番へのリリースをお願いします。

**Comment by opst-nemoto** [comment]
本番環境へのリリースが確認出来たため、クローズいたします。

**Comment by ghost** [comment]
リリースノートを記載したことをコメントして、closeしましょうか

https://github.com/matsuo-y/git-practice-lunch/releases/new?tag=v1.2

**Comment by opst-nemoto** [comment]
@fujimoto
リリースノートを追記いたしました。

**Comment by ghost** [comment]
追記したリリースノートのURLを記載してclose

https://github.com/matsuo-y/git-practice-lunch/releases/tag/v1.2

これですね
