### ISSUE TITLE
2016.10.31 conflict lunch

### ISSUE THREAD

**Issue by gonomk** [matsuo-y/git-practice-lunch#9]
connect matsuo-y/git-practice#13

10/31の昼ごはんを以下のサイトで公開できる

origin/#{N}-lunchから作業用(#{N}-lunch-{acount})ブランチをきり、origin/#{N}-lunchにPRしてマージする
コミットメッセージは、`fix` を記載しないようにし、誰の朝食か（どんな修正か）がわかる文言にする
PRのタイトルは、`fix` を記載しないようにし、誰の朝食かがわかる文言にする

作業担当者は、下記の通りとする
- issue作成者：郷野
- branch作成者：松尾
- 開発担当者(昼食報告、1名)：姜
- 検収担当者：上田
- リリース担当者：土井

ステージング環境： https://staging-git-practice-lunch.herokuapp.com/lunch/201610.html
本番環境：　https://matsuo-y.github.io/git-practice-lunch/lunch/201610.html

ただし、PR時ににはPR番号{N}の環境でサイトをブラウザで確認する
PR環境：　https://git-practice-lunch-pr-{N}.herokuapp.com/

**Comment by matsuo-y** [comment]
本日上田さんが忙しいそうなので、検収担当者を松尾に変更します。

**Comment by opst-D-Take** [comment]
リリース完了したのでcloseします。
